# Generated by Django 3.1.4 on 2021-01-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('schedulerID', models.AutoField(primary_key=True, serialize=False)),
                ('alarm', models.DateTimeField(default='')),
                ('Time', models.DateTimeField(default='')),
            ],
        ),
    ]
