# Generated by Django 3.1.4 on 2021-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='Time',
            field=models.IntegerField(default=''),
        ),
    ]
