# Generated by Django 3.1.4 on 2021-01-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210129_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='Time',
        ),
    ]
